services:
  - type: web
    name: demicstech-api
    env: python
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000